### ISSUE TITLE
[ADD] Custom horizontal slider class

### ISSUE THREAD

**Issue by yako-2792** [yako2792/photo-scanner#1]
Add `custom_horizontal_slider` class. Take a look at the attached picture.
Featuring:

* Label
* Slider
* Hind/comment
* GetValue method
* SetValue method

![demo_slider](https://github.com/user-attachments/assets/8fea5671-cf8d-4a70-b073-df8b2fef1163)

**Comment by yako2792** [comment]
![demo_slider](https://github.com/user-attachments/assets/e5d99c94-8c5b-4c84-9aab-b4d94315e0f9)

**Comment by yako-2792** [comment]
Done
